<?php
$joopdf_pp_Config['version']='1.0.1';
$joopdf_pp_Config['releasedate']='June 01 2011';
$joopdf_pp_Config['enabled']='1';
$joopdf_pp_Config['componentName']='JoostinaPDF';
$joopdf_pp_Config['componentOption']='joostinapdf';
$joopdf_pp_Config['standardTitleFont']='helveticaI';
$joopdf_pp_Config['standardTitleSize']='18';
$joopdf_pp_Config['standardFont']='helvetica';
$joopdf_pp_Config['standardSize']='12';
$joopdf_pp_Config['standardEncoding']='cp1251';
$joopdf_pp_Config['bulletChar']=' &bull; ';
$joopdf_pp_Config['marginTopFirstpage']='80';
$joopdf_pp_Config['marginBottomFirstpage']='30';
$joopdf_pp_Config['marginLeftFirstpage']='20';
$joopdf_pp_Config['marginRightFirstpage']='20';
$joopdf_pp_Config['marginTopOtherpages']='45';
$joopdf_pp_Config['marginBottomOtherpages']='30';
$joopdf_pp_Config['marginLeftOtherpages']='20';
$joopdf_pp_Config['marginRightOtherpages']='20';
$joopdf_pp_Config['templateFile']='template.pdf';
$joopdf_pp_Config['templatePageNoForFirst']='1';
$joopdf_pp_Config['templatePageNoForOther']='2';
$joopdf_pp_Config['titleHtmlFormat']='<div align="center"><font color="blue">{title}</font></div>';
$joopdf_pp_Config['showImages']='1';
$joopdf_pp_Config['imageDefaultAlign']='l';
$joopdf_pp_Config['showLinks']='1';
$joopdf_pp_Config['showTables']='0';
$joopdf_pp_Config['headerXpos']='10';
$joopdf_pp_Config['headerYpos']='8';
$joopdf_pp_Config['headerHtmlFormat']='<div align="center"><font color="blue" size="10">Сайт: {sitename} Ссылка: {siteurl} Заголовок: {title} - Создан: {date|j F Y}</font></div>';
$joopdf_pp_Config['footerXpos']='10';
$joopdf_pp_Config['footerYpos']='-25';
$joopdf_pp_Config['footerHtmlFormat']='<div><font color="blue" size="10">Страница {pageno} из {numberofpages} Дата печати: {currentdate|j F Y} {currenturl}</font></div>';
$joopdf_pp_Config['promotionFile']='0';
$joopdf_pp_Config['promotionPages']='2,last';
$joopdf_pp_Config['preventCopy']='1';
$joopdf_pp_Config['preventPrint']='0';
$joopdf_pp_Config['preventModify']='1';
$joopdf_pp_Config['cacheEnable']='0';
$joopdf_pp_Config['cacheDir']='E:/nimp/htdocs/joostina1212/cache';
$joopdf_pp_Config['cacheStrategy']='md';
$joopdf_pp_Config['cacheInvalidateTimes']='100';
$joopdf_pp_Config['cacheNameSeparator']='_';
$joopdf_pp_Config['imageForcedAlign']='1';
$joopdf_pp_Config['H1Format']='<font color="blue" size="16">{heading}</font>';
$joopdf_pp_Config['H1FormatSpace']='12';
$joopdf_pp_Config['H2Format']='<font color="blue" size="14">{heading}</font>';
$joopdf_pp_Config['H2FormatSpace']='12';
$joopdf_pp_Config['H3Format']='<font color="blue" size="12">{heading}</font>';
$joopdf_pp_Config['H3FormatSpace']='12';
$joopdf_pp_Config['H4Format']='<font color="blue" size="12">{heading}</font>';
$joopdf_pp_Config['H4FormatSpace']='12';
$joopdf_pp_Config['H5Format']='<font color="blue" size="12">{heading}</font>';
$joopdf_pp_Config['H5FormatSpace']='12';
$joopdf_pp_Config['H6Format']='<font color="blue" size="12">{heading}</font>';
$joopdf_pp_Config['H6FormatSpace']='12';
$joopdf_pp_Config['ignoreFontSize']='8';
$joopdf_pp_Config['customContentReplacements']='';
?>